/**
 */
package AlleKnotenFormartiert.provider;

import AlleKnotenFormartiert.util.AlleKnotenFormartiertAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AlleKnotenFormartiertItemProviderAdapterFactory extends AlleKnotenFormartiertAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AlleKnotenFormartiertItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.DocumentRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentRootItemProvider documentRootItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.DocumentRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentRootAdapter() {
		if (documentRootItemProvider == null) {
			documentRootItemProvider = new DocumentRootItemProvider(this);
		}

		return documentRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.FunctionResultColumnType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionResultColumnTypeItemProvider functionResultColumnTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.FunctionResultColumnType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionResultColumnTypeAdapter() {
		if (functionResultColumnTypeItemProvider == null) {
			functionResultColumnTypeItemProvider = new FunctionResultColumnTypeItemProvider(this);
		}

		return functionResultColumnTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.FunctionResultsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionResultsTypeItemProvider functionResultsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.FunctionResultsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionResultsTypeAdapter() {
		if (functionResultsTypeItemProvider == null) {
			functionResultsTypeItemProvider = new FunctionResultsTypeItemProvider(this);
		}

		return functionResultsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.FunctionResultType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionResultTypeItemProvider functionResultTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.FunctionResultType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionResultTypeAdapter() {
		if (functionResultTypeItemProvider == null) {
			functionResultTypeItemProvider = new FunctionResultTypeItemProvider(this);
		}

		return functionResultTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.InputsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputsTypeItemProvider inputsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.InputsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputsTypeAdapter() {
		if (inputsTypeItemProvider == null) {
			inputsTypeItemProvider = new InputsTypeItemProvider(this);
		}

		return inputsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.InputType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputTypeItemProvider inputTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.InputType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputTypeAdapter() {
		if (inputTypeItemProvider == null) {
			inputTypeItemProvider = new InputTypeItemProvider(this);
		}

		return inputTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.NewDataSetType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NewDataSetTypeItemProvider newDataSetTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.NewDataSetType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNewDataSetTypeAdapter() {
		if (newDataSetTypeItemProvider == null) {
			newDataSetTypeItemProvider = new NewDataSetTypeItemProvider(this);
		}

		return newDataSetTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.NodeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeTypeItemProvider nodeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.NodeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeTypeAdapter() {
		if (nodeTypeItemProvider == null) {
			nodeTypeItemProvider = new NodeTypeItemProvider(this);
		}

		return nodeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.NodeSystemType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeSystemTypeItemProvider nodeSystemTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.NodeSystemType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeSystemTypeAdapter() {
		if (nodeSystemTypeItemProvider == null) {
			nodeSystemTypeItemProvider = new NodeSystemTypeItemProvider(this);
		}

		return nodeSystemTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.NullNodeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NullNodeTypeItemProvider nullNodeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.NullNodeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNullNodeTypeAdapter() {
		if (nullNodeTypeItemProvider == null) {
			nullNodeTypeItemProvider = new NullNodeTypeItemProvider(this);
		}

		return nullNodeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.ResultsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultsTypeItemProvider resultsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.ResultsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultsTypeAdapter() {
		if (resultsTypeItemProvider == null) {
			resultsTypeItemProvider = new ResultsTypeItemProvider(this);
		}

		return resultsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.SourcesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SourcesTypeItemProvider sourcesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.SourcesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSourcesTypeAdapter() {
		if (sourcesTypeItemProvider == null) {
			sourcesTypeItemProvider = new SourcesTypeItemProvider(this);
		}

		return sourcesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.SourceType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SourceTypeItemProvider sourceTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.SourceType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSourceTypeAdapter() {
		if (sourceTypeItemProvider == null) {
			sourceTypeItemProvider = new SourceTypeItemProvider(this);
		}

		return sourceTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.ColumnDecorationsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnDecorationsTypeItemProvider columnDecorationsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.ColumnDecorationsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnDecorationsTypeAdapter() {
		if (columnDecorationsTypeItemProvider == null) {
			columnDecorationsTypeItemProvider = new ColumnDecorationsTypeItemProvider(this);
		}

		return columnDecorationsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.SourceColumnsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SourceColumnsTypeItemProvider sourceColumnsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.SourceColumnsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSourceColumnsTypeAdapter() {
		if (sourceColumnsTypeItemProvider == null) {
			sourceColumnsTypeItemProvider = new SourceColumnsTypeItemProvider(this);
		}

		return sourceColumnsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.SourceColumnType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SourceColumnTypeItemProvider sourceColumnTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.SourceColumnType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSourceColumnTypeAdapter() {
		if (sourceColumnTypeItemProvider == null) {
			sourceColumnTypeItemProvider = new SourceColumnTypeItemProvider(this);
		}

		return sourceColumnTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.ResultType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultTypeItemProvider resultTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.ResultType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultTypeAdapter() {
		if (resultTypeItemProvider == null) {
			resultTypeItemProvider = new ResultTypeItemProvider(this);
		}

		return resultTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.NewEClass148} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NewEClass148ItemProvider newEClass148ItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.NewEClass148}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNewEClass148Adapter() {
		if (newEClass148ItemProvider == null) {
			newEClass148ItemProvider = new NewEClass148ItemProvider(this);
		}

		return newEClass148ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.VisibleColumnsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VisibleColumnsTypeItemProvider visibleColumnsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.VisibleColumnsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVisibleColumnsTypeAdapter() {
		if (visibleColumnsTypeItemProvider == null) {
			visibleColumnsTypeItemProvider = new VisibleColumnsTypeItemProvider(this);
		}

		return visibleColumnsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.ItemType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ItemTypeItemProvider itemTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.ItemType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createItemTypeAdapter() {
		if (itemTypeItemProvider == null) {
			itemTypeItemProvider = new ItemTypeItemProvider(this);
		}

		return itemTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.ViewOptionsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewOptionsTypeItemProvider viewOptionsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.ViewOptionsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewOptionsTypeAdapter() {
		if (viewOptionsTypeItemProvider == null) {
			viewOptionsTypeItemProvider = new ViewOptionsTypeItemProvider(this);
		}

		return viewOptionsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.NodesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodesTypeItemProvider nodesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.NodesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodesTypeAdapter() {
		if (nodesTypeItemProvider == null) {
			nodesTypeItemProvider = new NodesTypeItemProvider(this);
		}

		return nodesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link AlleKnotenFormartiert.OutputType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputTypeItemProvider outputTypeItemProvider;

	/**
	 * This creates an adapter for a {@link AlleKnotenFormartiert.OutputType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputTypeAdapter() {
		if (outputTypeItemProvider == null) {
			outputTypeItemProvider = new OutputTypeItemProvider(this);
		}

		return outputTypeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (documentRootItemProvider != null) documentRootItemProvider.dispose();
		if (functionResultColumnTypeItemProvider != null) functionResultColumnTypeItemProvider.dispose();
		if (functionResultsTypeItemProvider != null) functionResultsTypeItemProvider.dispose();
		if (functionResultTypeItemProvider != null) functionResultTypeItemProvider.dispose();
		if (inputsTypeItemProvider != null) inputsTypeItemProvider.dispose();
		if (inputTypeItemProvider != null) inputTypeItemProvider.dispose();
		if (newDataSetTypeItemProvider != null) newDataSetTypeItemProvider.dispose();
		if (nodeTypeItemProvider != null) nodeTypeItemProvider.dispose();
		if (nodeSystemTypeItemProvider != null) nodeSystemTypeItemProvider.dispose();
		if (nullNodeTypeItemProvider != null) nullNodeTypeItemProvider.dispose();
		if (resultsTypeItemProvider != null) resultsTypeItemProvider.dispose();
		if (sourcesTypeItemProvider != null) sourcesTypeItemProvider.dispose();
		if (sourceTypeItemProvider != null) sourceTypeItemProvider.dispose();
		if (columnDecorationsTypeItemProvider != null) columnDecorationsTypeItemProvider.dispose();
		if (sourceColumnsTypeItemProvider != null) sourceColumnsTypeItemProvider.dispose();
		if (sourceColumnTypeItemProvider != null) sourceColumnTypeItemProvider.dispose();
		if (resultTypeItemProvider != null) resultTypeItemProvider.dispose();
		if (newEClass148ItemProvider != null) newEClass148ItemProvider.dispose();
		if (visibleColumnsTypeItemProvider != null) visibleColumnsTypeItemProvider.dispose();
		if (itemTypeItemProvider != null) itemTypeItemProvider.dispose();
		if (viewOptionsTypeItemProvider != null) viewOptionsTypeItemProvider.dispose();
		if (nodesTypeItemProvider != null) nodesTypeItemProvider.dispose();
		if (outputTypeItemProvider != null) outputTypeItemProvider.dispose();
	}

}
